// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCNMgl6zrwhjSFKMik6cna5Z2VZoSrWU8',
    appId: '1:326030694142:web:3d4ac13fc82a144265f7af',
    messagingSenderId: '326030694142',
    projectId: 'vocalabs-fac54',
    authDomain: 'vocalabs-fac54.firebaseapp.com',
    storageBucket: 'vocalabs-fac54.firebasestorage.app',
    measurementId: 'G-9K492SCZRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2I3cSTdPgW0bnVEjR-0BN-FNR1QJRfzE',
    appId: '1:326030694142:android:af5d2d1c0a0f04e365f7af',
    messagingSenderId: '326030694142',
    projectId: 'vocalabs-fac54',
    storageBucket: 'vocalabs-fac54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNyKEF4loSf-gKqm10b4E1bH6G28eMvtU',
    appId: '1:326030694142:ios:86cf86aa07a9420e65f7af',
    messagingSenderId: '326030694142',
    projectId: 'vocalabs-fac54',
    storageBucket: 'vocalabs-fac54.firebasestorage.app',
    iosClientId: '326030694142-q61kqm8ns63jba4p7ipbki3g6duc2fno.apps.googleusercontent.com',
    iosBundleId: 'com.example.vocallabsFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNyKEF4loSf-gKqm10b4E1bH6G28eMvtU',
    appId: '1:326030694142:ios:86cf86aa07a9420e65f7af',
    messagingSenderId: '326030694142',
    projectId: 'vocalabs-fac54',
    storageBucket: 'vocalabs-fac54.firebasestorage.app',
    iosClientId: '326030694142-q61kqm8ns63jba4p7ipbki3g6duc2fno.apps.googleusercontent.com',
    iosBundleId: 'com.example.vocallabsFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCNMgl6zrwhjSFKMik6cna5Z2VZoSrWU8',
    appId: '1:326030694142:web:a90f293d3252d6aa65f7af',
    messagingSenderId: '326030694142',
    projectId: 'vocalabs-fac54',
    authDomain: 'vocalabs-fac54.firebaseapp.com',
    storageBucket: 'vocalabs-fac54.firebasestorage.app',
    measurementId: 'G-V697YCHDLN',
  );
}